function out = episode_default()
%
% EPISODE_DEFAULT Returns default parameters for the EPISODE protocol
%
% Copyright 2006-2011 dmeliza@uchicago.edu; see LICENSE

out = struct('instrument',...
    param_struct('Instrument', 'list', 1, GetInstrumentNames),...
    'data_mode',...
    param_struct('Data Storage', 'list', 1, {'daqfile', 'matfile'}),...
    'ep_repeats',...
    param_struct('Ep. Repeats', 'value', Inf),...
    'ep_length',...
    param_struct('Ep. Length', 'value', 1000, [], 'ms'),...
    'ep_interval',...
    param_struct('Ep. Interval', 'value', 2000, [], 'ms'),...
    'waveform',...
    param_struct('Command Signal', 'object', waveform, [], [],...
        {@WaveformEditor 'modal'}));
