function out = episode_default()
%
% EPISODE_DEFAULT Returns default parameters for the EPISODE protocol
%
% $Id: episode_default.m,v 1.2 2006/01/21 01:22:30 meliza Exp $

out = struct('instrument',...
    param_struct('Instrument', 'list', 1, GetInstrumentNames),...
    'data_mode',...
    param_struct('Data Storage', 'list', 1, {'daqfile', 'matfile'}),...
    'ep_length',...
    param_struct('Ep. Length', 'value', 1000, [], 'ms'),...
    'ep_interval',...
    param_struct('Ep. Interval', 'value', 2000, [], 'ms'),...
    'waveform',...
    param_struct('Command Signal', 'fixed', '', [], [], @WaveformDialog));
