function out = playstimulus_default()
%
% PLAYSTIMULUS_DEFAULT Returns default parameters for the PLAYSTIMULUS protocol
%
% edits 2011.03.18 MK 
% 'max_pos_cur' The maximum positive current (10ms moving average) that the cell will experience.
% 'max_neg_cur' The maximum negative current (10ms moving average) that the cell will experience.
% these will be use to rescale the current waveform
instruments = GetInstrumentNames;
channels = GetInstrumentChannelNames(instruments{1},'input');

out = struct('instrument',...
    param_struct('Instrument', 'list', 1, instruments),...
    'data_output',...
    param_struct('Output','list', 1, channels),...
    'data_mode',...
    param_struct('Data Storage', 'list', 1, {'daqfile', 'matfile'}),...
    'ep_repeats',...
    param_struct('Ep. Repeats', 'value', Inf),...
    'ep_interval',...
    param_struct('Ep. Interval', 'value', 2000, [], 'ms'),...
    'max_pos_cur',...
    param_struct('Max +|nA|', 'value', 1.0),...
    'max_neg_cur',...
    param_struct('Max -|nA|', 'value', 1.0),...
    'stimulus',...
    param_struct('Stimulus File', 'File_in', ''),...
    'stim_list',...
    param_struct('Stimulus list', 'hidden', []));
