function out = playmovie_default()
%
% PLAYMOVIE_DEFAULT Returns default parameters for the PLAYMOVIE protocol
%
% $Id: playmovie_default.m,v 1.1 2006/01/25 01:31:39 meliza Exp $

out = struct('instrument',...
    param_struct('Instrument', 'list', 1, GetInstrumentNames),...
    'data_mode',...
    param_struct('Data Storage', 'list', 1, {'daqfile', 'matfile'}),...
    'movie_repeat',...
    param_struct('Movie Repeats', 'value', 1),...
    'update_rate',...
    param_struct('Update Rate', 'value', 5, [], 'Hz'),...
    'ep_interval',...
    param_struct('Intermovie Interval', 'value', 2000, [], 'ms'),...
    'waveform',...
    param_struct('Command Signal', 'fixed', '', [], [], @WaveformDialog));
