function out = playstimulus_default()
%
% PLAYSTIMULUS_DEFAULT Returns default parameters for the PLAYSTIMULUS protocol
%

instruments = GetInstrumentNames;
channels = GetInstrumentChannelNames(instruments{1},'input');

out = struct('instrument',...
    param_struct('Instrument', 'list', 1, instruments),...
    'data_output',...
    param_struct('Output','list', 1, channels),...
    'data_mode',...
    param_struct('Data Storage', 'list', 1, {'daqfile', 'matfile'}),...
    'ep_repeats',...
    param_struct('Ep. Repeats', 'value', Inf),...
    'ep_interval',...
    param_struct('Ep. Interval', 'value', 2000, [], 'ms'),...
    'stim_mean',...
    param_struct('Stim. Mean', 'value', 0.0),...
    'stim_range',...
    param_struct('Stim. Range', 'value', 1.0),...
    'stimulus',...
    param_struct('Stimulus File', 'File_in', ''),...
    'stim_cache',...
    param_struct('Cached stimulus', 'hidden', []));
