function handle = InitUIObject(module, tag, creation_string, varargin)
% INITUIOBJECT Creates a GUI object and adds its handle to the control
% structure. 
%
% Use this instead of INITUICONTROL when the object cannot be generated by
% a call to UICONTROL (e.g. axes, activex controls). Note that the calling
% function (or <creation_string>) is responsible for setting the parent of
% the object correctly; <module> is used only to store the object in the
% control structure.
%
% handle = INITUIOBJECT(module, tag, creation_string, [properties])
%
%   module          - the module in wc
%   tag             - the name used to refer to the object
%   creation_string - an evalable string that generates the object. Note
%                     that this is called in the workspace of the calling 
%                     function, so variables in that workspace can be 
%                     used here.
%   properties      - optional comma-delim used to the properties of 
%                     the object
%
%   $Id: InitUIObject.m,v 1.1 2006/01/10 20:59:52 meliza Exp $

if nargin < 3
    error('METAPHYS:InitUIObject:argumentError','Not enough arguments');
end

%% Generate the object
h = evalin('caller',creation_string, []);

if ~ishandle(h)
    error('METAPHYS:InitUIObject:objectInitializationError',...
        'Unable to initialize object. Check syntax');
end

%% Set object parent and other properties
if nargin > 3
    set(h, varargin{:});
end

InitUIParam(module, tag, h);

handle = h;